import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./components/Header/Header";
import { ImSearch } from "react-icons/im";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const navMenu = [
  {
    text: "Movies",
    url: "#",
  },
  {
    text: "Tv Shows",
    url: "#",
  },
  {
    text: "People",
    url: "/person",
  },
  {
    text: "More",
    url: "#",
  },
];
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header
          logo={{
            imgSrc: "header-logo.svg",
            url: "/",
            altText: "header-logo",
          }}
          ActionIcon={ImSearch}
          menu={{ menuLinks: navMenu }}
        />
        {children}
      </body>
    </html>
  );
}
